Repository dnum-mi/vue-dsfr, pull requests merged in 2021-07, with the labels that each got.

#2 Refacto/migrate to vite
  .storybook/main.js
  babel.config.js
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  vite.config.js
Labels: enhancement

#1 Feat/dsfr input
  src/assets/reset-dsfr.css
  src/components/DsfrButton/DsfrButton.stories.js
  src/components/DsfrInput/DsfrInput.spec.js
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
  src/utils/random-utils.js
  src/utils/random-utils.spec.js
Labels: enhancement

#3 feat: :sparkles: Implémente DsfrSearchBar
  src/assets/reset-dsfr.css
  src/components/DsfrButton/DsfrButton.vue
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrSearchBar/DsfrSearchBar.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.stories.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
Labels: enhancement

#4 fix: :rotating_light: Fix ::v-deep deprecation warning
  src/components/DsfrButton/DsfrButton.stories.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
Labels: lint warning

#5 feat: :sparkles: Implémente version large barre recherche
  src/components/DsfrSearchBar/DsfrSearchBar.stories.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
Labels: enhancement

#6 feat: :sparkles: Implémente DsfrRadioButton
  .storybook/preview.js
  jest.config.js
  package-lock.json
  package.json
  src/assets/objects-dsfr.css
  src/assets/reset-dsfr.css
  src/assets/utils-dsfr.css
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrRadioButton/DsfrRadioButton.spec.js
  src/components/DsfrRadioButton/DsfrRadioButton.stories.js
  src/components/DsfrRadioButton/DsfrRadioButton.vue
  src/components/DsfrRadioButton/DsfrRadioButtonSet.spec.js
  src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.js
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
  src/components/DsfrSearchBar/DsfrSearchBar.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
  src/main.css
  src/utils/random-utils.js
  tests/unit/jest-setup.js
Labels: enhancement

#11 Fix/radio button inline spacing
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
Labels: bug

#12 docs: :memo: Ajoute une documentation
  README.md
  src/stories/docs/dev.stories.mdx
  src/stories/docs/guide.stories.mdx
  src/stories/docs/intro.stories.mdx
Labels: documentation

#16 feat/dsfr card
  src/components/DsfrCard/DsfrCard.spec.js
  src/components/DsfrCard/DsfrCard.stories.js
  src/components/DsfrCard/DsfrCard.vue
Labels: enhancement
