Repository dnum-mi/vue-dsfr, pull requests merged in 2021-11, with the labels that each got.

#134 Fix/tiny fixes
  package-lock.json
  package.json
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
  src/components/DsfrSearchBar/DsfrSearchBar.stories.js
Labels: bug

#136 fix/select and toggle
  src/components/DsfrSelect/DsfrSelect.vue
  src/components/DsfrToggleSwitch/DsfrToggleSwitch.vue
Labels: bug

#138 feat/dsfr tile
  src/components/DsfrTabs/DsfrTabs.spec.js
  src/components/DsfrTag/DsfrTag.spec.js
  src/components/DsfrTile/DsfrTile.spec.js
  src/components/DsfrTile/DsfrTile.stories.js
  src/components/DsfrTile/DsfrTile.vue
  src/components/DsfrTile/DsfrTiles.spec.js
  src/components/DsfrTile/DsfrTiles.stories.js
  src/components/DsfrTile/DsfrTiles.vue
  src/components/DsfrTile/tiles.css
  src/components/index.js
Labels: enhancement

#140 fix: :lipstick: Corrige le mode dark du composant Tuile
  src/components/DsfrTile/DsfrTile.vue
  src/components/index.js
Labels: bug

#142 chore: :bug: Supprime un warning parasite lors du build
  src/assets/core.css
  src/assets/forms.css
  src/components/DsfrCallout/callouts.css
  src/components/DsfrCheckbox/checkboxes.css
  src/components/DsfrFollow/follow.css
  src/components/DsfrFooter/footer.css
  src/components/DsfrMedia/content.css
  src/components/DsfrQuote/quotes.css
  src/components/DsfrTabs/tabs.css
Labels: bug

#141 feat: :sparkles: Implémente le composant "Mise en exergue"
  src/components/DsfrHighlight/DsfrHighlight.spec.js
  src/components/DsfrHighlight/DsfrHighlight.stories.js
  src/components/DsfrHighlight/DsfrHighlight.vue
  src/components/DsfrHighlight/highlights.css
  src/components/index.js
Labels: enhancement

#145 feat: :sparkles: Implémente le composant accordéon
  src/components/DsfrAccordion/DsfrAccordion.spec.js
  src/components/DsfrAccordion/DsfrAccordion.stories.js
  src/components/DsfrAccordion/DsfrAccordion.vue
  src/components/DsfrAccordion/DsfrAccordionsGroup.stories.js
  src/components/DsfrAccordion/DsfrAccordionsGroup.vue
  src/components/DsfrAccordion/accordions.css
  src/components/index.js
Labels: enhancement

#147 feat: :sparkles: Implémente le composant Navigation
  src/components/DsfrNavigation/DsfrNavigation.spec.js
  src/components/DsfrNavigation/DsfrNavigation.stories.js
  src/components/DsfrNavigation/DsfrNavigation.vue
  src/components/DsfrNavigation/DsfrNavigationItem.vue
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.stories.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.vue
  src/components/DsfrNavigation/DsfrNavigationMegaMenuCategory.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenuCategory.stories.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenuCategory.vue
  src/components/DsfrNavigation/DsfrNavigationMenu.stories.js
  src/components/DsfrNavigation/DsfrNavigationMenu.vue
  src/components/DsfrNavigation/DsfrNavigationMenuLink.stories.js
  src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
  src/components/DsfrNavigation/navigation-vue-dsfr.css
  src/components/DsfrNavigation/navigation.css
  src/icons.js
Labels: enhancement

#148 feat: :sparkles: Garde le focus à l'intérieur de la modale
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/DsfrModal/DsfrModal.vue
Labels: enhancement

#149 refactor: :recycle: Utilise les derniers styles du DSFR
  src/components/DsfrCard/DsfrCard.vue
  src/components/DsfrCard/card.css
Labels: refactoring

#160 Docs/vue3 vite nuxt3 notes
  src/stories/docs/01-intro.stories.mdx
  src/stories/docs/02-guide.stories.mdx
Labels: documentation
