Repository dnum-mi/vue-dsfr, pull requests merged in 2021-12, with the labels that each got.

#165 feat: :sparkles: Ajouter la props disabled sur DsfrInput
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#168 tech/upgrade storybook
  .eslintrc.js
  .storybook/main.js
  package-lock.json
  package.json
Labels: tech

#175 fix: :lipstick: Harmonise margin et font size avec le select
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#178 fix: :lipstick: Corrige le contraste des couleurs des tags
  src/assets/variables-dsfr.css
Labels: bug

#191 feat: :sparkles: Ajout de la props isTextarea, permettant de mettre l…
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
Labels: enhancement

#195 Fix/header menu link path
  index.html
  src/components/DsfrHeader/DsfrHeader.stories.js
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/demo-app/App.vue
  src/demo-app/main.js
  src/demo-app/router.js
  src/demo-app/views/AboutUs.vue
  src/demo-app/views/AppHome.vue
Labels: bug

#197 Feat/ajoute composable pour theme
  .eslintrc.js
  .storybook/preview.js
  jsdoc-config.json
  package-lock.json
  package.json
  src/composables.js
  src/demo-app/App.vue
  src/index.js
  src/stories/composables/composables.stories.mdx
  tsconfig.json
  types/composables.d.ts
Labels: enhancement
