Repository dnum-mi/vue-dsfr, pull requests merged in 2022-01, with the labels that each got.

#203 Feat/dsfr pagination
  cypress.json
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.e2e.js
  src/components/DsfrPagination/DsfrPagination.e2e.js
  src/components/DsfrPagination/DsfrPagination.spec.js
  src/components/DsfrPagination/DsfrPagination.stories.js
  src/components/DsfrPagination/DsfrPagination.vue
  src/components/DsfrPagination/pagination.main.css
  src/components/index.js
  src/icons.js
Labels: enhancement

#213 feat: :sparkles: Implémente l'upload de fichiers
  jsconfig.json
  src/components/DsfrFileUpload/DsfrFileUpload.spec.js
  src/components/DsfrFileUpload/DsfrFileUpload.stories.js
  src/components/DsfrFileUpload/DsfrFileUpload.vue
  src/components/DsfrFileUpload/upload.css
  src/components/DsfrHeader/DsfrHeader.e2e.js
Labels: enhancement

#216 refactor: :recycle: Refacto structure fichiers vue
  src/components/DsfrAlert/DsfrAlert.vue
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
  src/components/DsfrButton/DsfrButton.vue
  src/components/DsfrCard/DsfrCard.vue
  src/components/DsfrCheckbox/DsfrCheckbox.vue
  src/components/DsfrCheckbox/DsfrCheckboxSet.vue
  src/components/DsfrFooter/DsfrFooterLinkList.vue
  src/components/DsfrFooter/DsfrFooterPartners.vue
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrHeader/DsfrHeaderMenuLinks.vue
  src/components/DsfrHighlight/DsfrHighlight.vue
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrLogo/DsfrLogo.vue
  src/components/DsfrQuote/DsfrQuote.vue
  src/components/DsfrRadioButton/DsfrRadioButton.vue
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
  src/components/DsfrSearchBar/DsfrSearchBar.vue
  src/components/DsfrSkipLinks/DsfrSkipLinks.vue
  src/components/DsfrTable/DsfrTable.vue
  src/components/DsfrTabs/DsfrTabContent.vue
  src/components/DsfrTabs/DsfrTabItem.vue
  src/components/DsfrTabs/DsfrTabs.vue
  src/components/DsfrToggleSwitch/DsfrToggleSwitch.vue
Labels: refactoring

#222 fix: :bug: Ajout de * si le champs est requis
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#220 fix([DsfrNavigationMenu]): :bug: Transmit toggle-id event to parent
  src/components/DsfrNavigation/DsfrNavigationMenu.vue
Labels: bug
