Repository dnum-mi/vue-dsfr, pull requests merged in 2022-04, with the labels that each got.

#303 docs/improve docs
  package.json
  src/components/DsfrAccordion/DsfrAccordion.stories.js
  src/components/DsfrAccordion/DsfrAccordion.vue
  src/components/DsfrAccordion/DsfrAccordionsGroup.stories.js
  src/components/DsfrAlert/DsfrAlert.stories.js
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.stories.js
  src/components/DsfrCallout/DsfrCallout.stories.js
  src/components/DsfrCheckbox/DsfrCheckbox.stories.js
  src/components/DsfrConsent/DsfrConsent.stories.js
  src/components/DsfrFileUpload/DsfrFileUpload.stories.js
  src/components/DsfrFollow/DsfrFollow.vue
  src/components/DsfrFooter/DsfrFooter.stories.js
  src/components/DsfrFooter/DsfrFooter.vue
  src/components/DsfrHeader/DsfrHeader.stories.js
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInputGroup.stories.js
  src/components/DsfrMedia/DsfrPicture.stories.js
  src/components/DsfrModal/DsfrModal.stories.js
  src/components/DsfrNavigation/DsfrNavigation.stories.js
  src/components/DsfrNavigation/DsfrNavigationItem.stories.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.stories.js
  src/components/DsfrNavigation/DsfrNavigationMenu.stories.js
  src/components/DsfrNavigation/DsfrNavigationMenuItem.vue
  src/components/DsfrNavigation/DsfrNavigationMenuLink.stories.js
  src/components/DsfrPagination/DsfrPagination.stories.js
  src/components/DsfrPagination/DsfrPagination.vue
  src/components/DsfrQuote/DsfrQuote.stories.js
  src/components/DsfrQuote/DsfrQuote.vue
  src/components/DsfrRadioButton/DsfrRadioButton.stories.js
  src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.js
  src/components/DsfrSearchBar/DsfrSearchBar.stories.js
  src/components/DsfrSelect/DsfrSelect.stories.js
  src/components/DsfrShare/DsfrShare.stories.js
  src/components/DsfrSideMenu/DsfrSideMenu.stories.js
  src/components/DsfrSideMenu/DsfrSideMenuLink.stories.js
  src/components/DsfrSideMenu/DsfrSideMenuLink.vue
  src/components/DsfrSideMenu/DsfrSideMenuListItem.stories.js
  src/components/DsfrSideMenu/DsfrSideMenuListItem.vue
  src/components/DsfrSkipLinks/DsfrSkipLinks.stories.js
  src/components/DsfrTable/DsfrTable.stories.js
  src/components/DsfrTable/DsfrTable.vue
  src/components/DsfrTable/DsfrTableCell.stories.js
  src/components/DsfrTable/DsfrTableCell.vue
  src/components/DsfrTable/DsfrTableHeader.stories.js
  src/components/DsfrTable/DsfrTableRow.stories.js
  src/components/DsfrTabs/DsfrTabItem.stories.js
  src/components/DsfrTabs/DsfrTabs.stories.js
  src/components/DsfrTabs/DsfrTabs.vue
  src/components/DsfrToggleSwitch/DsfrToggleSwitch.stories.js
  src/demo-app/App.vue
  types/components/DsfrSelect/DsfrSelect.vue.d.ts
  types/components/DsfrTable/DsfrTableCell.vue.d.ts
Labels: documentation

#309 feat: :sparkles: Implémente la version 1.4.1 du DSFR
  package-lock.json
  package.json
  src/components/DsfrAccordion/DsfrAccordion.stories.js
  src/components/DsfrAccordion/DsfrAccordion.vue
  src/components/DsfrAlert/DsfrAlert.e2e.js
  src/components/DsfrAlert/DsfrAlert.spec.js
  src/components/DsfrAlert/DsfrAlert.vue
  src/components/DsfrBadge/DsfrBadge.spec.js
  src/components/DsfrBadge/DsfrBadge.stories.js
  src/components/DsfrBadge/DsfrBadge.vue
  src/components/DsfrButton/DsfrButton.stories.js
  src/components/DsfrButton/DsfrButton.vue
  src/components/DsfrFollow/DsfrFollow.e2e.js
  src/components/DsfrFollow/DsfrSocialNetworks.spec.js
  src/components/DsfrFollow/DsfrSocialNetworks.vue
  src/components/DsfrFranceConnect/DsfrFranceConnect.spec.js
  src/components/DsfrFranceConnect/DsfrFranceConnect.stories.js
  src/components/DsfrFranceConnect/DsfrFranceConnect.vue
  src/components/DsfrHeader/DsfrHeader.stories.js
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrHeader/DsfrHeaderMenuLinks.vue
  src/components/DsfrMedia/DsfrMedia.e2e.js
  src/components/DsfrMedia/DsfrVideo.spec.js
  src/components/DsfrMedia/DsfrVideo.vue
  src/components/DsfrModal/DsfrModal.e2e.js
  src/components/DsfrModal/DsfrModal.spec.js
  src/components/DsfrModal/DsfrModal.vue
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.vue
  src/components/DsfrPagination/DsfrPagination.vue
  src/components/DsfrShare/DsfrShare.vue
  src/components/index.js
  src/stories/fondamentaux/classes-utilitaires.stories.mdx
  src/stories/fondamentaux/titles.stories.js
  types/components/DsfrBadge/DsfrBadge.vue.d.ts
  types/components/DsfrFranceConnect/DsfrFranceConnect.vue.d.ts
Labels: enhancement

#305 tech/upgrade dependencies
  .storybook/main.js
  package-lock.json
  package.json
  vitest.config.js
Labels: tech

#312 fix(build): :green_heart: Corrige le bug de 'oh-vue-icons/icons/ri/in…
  rollup.config.js
Labels: bug

#315 chore: ⬆️ Met à jour les dépendances
  package-lock.json
  package.json
Labels: tech

#316 feat: :label: Ajoute le type pour l’export par défaut (le plugin)
  types/index.d.ts
Labels: types

#317 feat: :memo: Améliore la documentation pour l’utilisation d’icônes
  src/stories/fondamentaux/icones-officielles.stories.mdx
  src/stories/fondamentaux/icones-personnalisees.stories.mdx
Labels: documentation

#318 docs: 📝 Améliore la documentation d’introduction
  src/stories/docs/01-intro.stories.mdx
Labels: documentation

#328 feat: :sparkles: Permet personnalisation des labels des champs requis
  src/components/DsfrCheckbox/DsfrCheckbox.stories.js
  src/components/DsfrCheckbox/DsfrCheckbox.vue
  src/components/DsfrCheckbox/DsfrCheckboxSet.stories.js
  src/components/DsfrCheckbox/DsfrCheckboxSet.vue
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrRadioButton/DsfrRadioButtonSet.stories.js
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
  src/demo-app/App.vue
Labels: enhancement

#331 feat: :sparkles: Permet personnalisation de l’info "chp requis" pour …
  package-lock.json
  src/components/DsfrSelect/DsfrSelect.stories.js
  src/components/DsfrSelect/DsfrSelect.vue
Labels: enhancement

#333 RC13
  package-lock.json
  src/components/DsfrSelect/DsfrSelect.stories.js
  src/components/DsfrSelect/DsfrSelect.vue
Labels: enhancement

#336 fix: :bug: Utilise toujours router-link pour les liens internes
  package.json
  rollup.config.js
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
  src/components/DsfrCard/DsfrCard.vue
  src/components/DsfrConsent/DsfrConsent.vue
  src/components/DsfrFooter/DsfrFooter.vue
  src/components/DsfrFooter/DsfrFooterLinkList.vue
  src/components/DsfrHeader/DsfrHeader.stories.js
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
  src/components/DsfrSideMenu/DsfrSideMenuLink.stories.js
  src/components/DsfrSideMenu/DsfrSideMenuLink.vue
  src/components/DsfrSideMenu/DsfrSideMenuList.stories.js
  src/components/DsfrSideMenu/DsfrSideMenuList.vue
  src/components/DsfrTag/DsfrTag.vue
  src/components/DsfrTile/DsfrTile.vue
  types/components/DsfrCard/DsfrCard.vue.d.ts
  types/components/DsfrConsent/DsfrConsent.vue.d.ts
  types/components/DsfrFooter/DsfrFooter.vue.d.ts
  types/components/DsfrFooter/DsfrFooterLinkList.vue.d.ts
  types/components/DsfrHeader/DsfrHeader.vue.d.ts
  types/components/DsfrHeader/DsfrHeaderMenuLink.vue.d.ts
  types/components/DsfrNavigation/DsfrNavigationMenuLink.vue.d.ts
  types/components/DsfrSideMenu/DsfrSideMenuLink.vue.d.ts
  types/components/DsfrSideMenu/DsfrSideMenuList.vue.d.ts
  types/components/DsfrTag/DsfrTag.vue.d.ts
  types/components/DsfrTile/DsfrTile.vue.d.ts
Labels: bug

#356 chore: :construction_worker: Utilise l’utilisateur gouvminint au lieu…
  .github/workflows/publish-release.yml
  .npmrc
  package-lock.json
  package.json
Labels: tech

#358 fix: :bug: Corrige required for Select, RadioButtonSet et CheckboxSet
  src/components/DsfrCheckbox/DsfrCheckboxSet.vue
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
  src/components/DsfrSelect/DsfrSelect.vue
Labels: bug
