Repository dnum-mi/vue-dsfr, pull requests merged in 2022-03, with the labels that each got.

#247 feat: :sparkles: Implémente le composant Gestionnaire de consentement
  src/components/DsfrConsent/DsfrConsent.spec.js
  src/components/DsfrConsent/DsfrConsent.stories.js
  src/components/DsfrConsent/DsfrConsent.vue
  src/components/DsfrTag/DsfrTag.vue
  src/components/index.js
Labels: bug, enhancement

#250 feat: :sparkles: Ajout d'un slot pour les svg
  src/components/DsfrMedia/DsfrPicture.stories.js
  src/components/DsfrMedia/DsfrPicture.vue
Labels: enhancement

#255 Feat/init dsfr with vue mode
  src/components/DsfrAccordion/DsfrAccordion.stories.js
  src/components/DsfrAccordion/DsfrAccordion.vue
  src/components/DsfrHeader/DsfrHeader.vue
  src/demo-app/App.vue
  src/index.js
  src/init-dsfr.js
Labels: documentation, enhancement

#264 fix: :bug: Corrige l'oubli de l'indice du composant champ de saisie
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrInput/DsfrInputGroup.stories.js
  src/components/DsfrInput/DsfrInputGroup.vue
Labels: bug, enhancement

#268 feat: :sparkles: Ajoute la props type au composant input
  src/components/DsfrAlert/DsfrAlert.vue
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
  src/components/DsfrInput/DsfrInputGroup.stories.js
  src/components/DsfrInput/DsfrInputGroup.vue
Labels: enhancement

#269 feat: :sparkles: Ajout d'un slot au sein de la mise en exergue
  src/components/DsfrHighlight/DsfrHighlight.stories.js
  src/components/DsfrHighlight/DsfrHighlight.vue
Labels: enhancement

#272 Fix/header
  src/components/DsfrCheckbox/DsfrCheckboxSet.stories.js
  src/components/DsfrCheckbox/DsfrCheckboxSet.vue
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#277 fix: :bug: Corrige la prise en compte de l'indice du champ de saisie
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#280 refacto: :recycle: Use Vitest instead of Jest
  package-lock.json
  package.json
  src/components/DsfrAccordion/DsfrAccordion.spec.js
  src/components/DsfrAlert/DsfrAlert.spec.js
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.spec.js
  src/components/DsfrButton/DsfrButton.spec.js
  src/components/DsfrButton/DsfrButtonGroup.spec.js
  src/components/DsfrCallout/DsfrCallout.spec.js
  src/components/DsfrHeader/DsfrHeader.spec.js
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrModal/DsfrModal.spec.js
  src/components/DsfrNavigation/DsfrNavigation.spec.js
  src/components/DsfrNavigation/DsfrNavigationItem.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenuCategory.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenu.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenuItem.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenuLink.spec.js
  src/components/DsfrPagination/DsfrPagination.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
  src/components/DsfrSideMenu/DsfrSideMenu.spec.js
  src/components/DsfrSideMenu/DsfrSideMenu.vue
  src/components/DsfrTable/DsfrTableCell.spec.js
  src/components/DsfrTable/DsfrTableHeader.spec.js
  src/components/DsfrTable/DsfrTableHeaders.spec.js
  src/components/DsfrTable/DsfrTableRow.spec.js
  src/components/DsfrTabs/DsfrTabs.spec.js
  src/components/DsfrTag/DsfrTag.spec.js
  src/components/DsfrTile/DsfrTile.spec.js
  src/components/DsfrTile/DsfrTile.vue
  src/components/DsfrTile/DsfrTiles.spec.js
  src/components/DsfrToggleSwitch/DsfrToggleSwitch.spec.js
  tests/unit/test-utils.js
  tests/unit/vitest-setup.js
  vitest.config.js
Labels: tech

#282 feat: :sparkles: Implémente la possibilité de changer les liens de l'…
  src/components/DsfrFooter/DsfrFooter.e2e.js
  src/components/DsfrFooter/DsfrFooter.stories.js
  src/components/DsfrFooter/DsfrFooter.vue
  src/constants.js
Labels: enhancement

#283 fix: :bug: Corrige la gestion d'undefined pour l'indice du champ de s…
  src/components/DsfrInput/DsfrInput.vue
Labels: bug

#284 RC4
  package-lock.json
  package.json
  src/components/DsfrAccordion/DsfrAccordion.spec.js
  src/components/DsfrAlert/DsfrAlert.spec.js
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.spec.js
  src/components/DsfrButton/DsfrButton.spec.js
  src/components/DsfrButton/DsfrButtonGroup.spec.js
  src/components/DsfrCallout/DsfrCallout.spec.js
  src/components/DsfrFooter/DsfrFooter.e2e.js
  src/components/DsfrFooter/DsfrFooter.stories.js
  src/components/DsfrFooter/DsfrFooter.vue
  src/components/DsfrHeader/DsfrHeader.spec.js
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrInput/DsfrInput.stories.js
  src/components/DsfrModal/DsfrModal.spec.js
  src/components/DsfrNavigation/DsfrNavigation.spec.js
  src/components/DsfrNavigation/DsfrNavigationItem.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenu.spec.js
  src/components/DsfrNavigation/DsfrNavigationMegaMenuCategory.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenu.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenuItem.spec.js
  src/components/DsfrNavigation/DsfrNavigationMenuLink.spec.js
  src/components/DsfrPagination/DsfrPagination.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.spec.js
  src/components/DsfrSearchBar/DsfrSearchBar.vue
  src/components/DsfrSideMenu/DsfrSideMenu.spec.js
  src/components/DsfrSideMenu/DsfrSideMenu.vue
  src/components/DsfrTable/DsfrTableCell.spec.js
  src/components/DsfrTable/DsfrTableHeader.spec.js
  src/components/DsfrTable/DsfrTableHeaders.spec.js
  src/components/DsfrTable/DsfrTableRow.spec.js
  src/components/DsfrTabs/DsfrTabs.spec.js
  src/components/DsfrTag/DsfrTag.spec.js
  src/components/DsfrTile/DsfrTile.spec.js
  src/components/DsfrTile/DsfrTile.vue
  src/components/DsfrTile/DsfrTiles.spec.js
  src/components/DsfrToggleSwitch/DsfrToggleSwitch.spec.js
  src/constants.js
  tests/unit/test-utils.js
  tests/unit/vitest-setup.js
  vitest.config.js
Labels: enhancement

#301 feat: :sparkles: Permet la personnalisation des liens obligatoires
  src/components/DsfrFooter/DsfrFooter.vue
Labels: enhancement

#299 feat([DsfrAccordion]): :sparkles: Customisation du titre
  src/components/DsfrAccordion/DsfrAccordion.stories.js
  src/components/DsfrAccordion/DsfrAccordion.vue
Labels: enhancement
