Repository dnum-mi/vue-dsfr, pull requests merged in 2023-12, with the labels that each got.

#662 ci(husky): remplacement yorkie par husky
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  commitlint.config.cjs
  package-lock.json
  package.json
Labels: ci

#682 feat: :sparkles: Nouveau composant Segmented (Contrôle Segmenté)
  package-lock.json
  package.json
  src/components/DsfrSegmented/DsfrSegmented.spec.ts
  src/components/DsfrSegmented/DsfrSegmented.stories.ts
  src/components/DsfrSegmented/DsfrSegmented.types.ts
  src/components/DsfrSegmented/DsfrSegmented.vue
  src/components/DsfrSegmented/DsfrSegmentedSet.e2e.ts
  src/components/DsfrSegmented/DsfrSegmentedSet.spec.ts
  src/components/DsfrSegmented/DsfrSegmentedSet.stories.ts
  src/components/DsfrSegmented/DsfrSegmentedSet.vue
Labels: enhancement, dsfr

#691 docs: :memo: ajoute la documentation pour segmented
  .vitepress/config.ts
  .vitepress/theme/icons.ts
  docs/types.md
  src/components/DsfrBackToTop/DsfrBactToTop.md
  src/components/DsfrSegmented/DsfrSegmented.md
  src/components/DsfrSegmented/DsfrSegmented.vue
  src/components/DsfrSegmented/DsfrSegmentedSet.md
  src/components/DsfrSegmented/DsfrSegmentedSet.stories.ts
  src/components/DsfrSegmented/DsfrSegmentedSet.vue
  src/components/DsfrSegmented/docs-demo/DsfrSegmentedDemo.vue
Labels: documentation

#696 695 ajouter la documentation vitepress pour dsfrcard
  .vitepress/config.ts
  .vitepress/theme/icons.ts
  .vitepress/theme/style.css
  .vscode/settings.json
  docs/composants.md
  src/components/DsfrButton/DsfrButton.md
  src/components/DsfrButton/DsfrButton.vue
  src/components/DsfrButton/docs-demo/DsfrButtonExample.vue
  src/components/DsfrCard/DsfrCard.md
  src/components/DsfrCard/docs-demo/DsfrCardDemo.vue
Labels: documentation

#699 docs: :memo: ajoute la doc vitepress pour DsfrBreadcrumb
  .vitepress/config.ts
  .vitepress/theme/index.ts
  docs/composants.md
  src/components/DsfrBreadcrumb/DsfrBreadcrumb.md
  src/components/DsfrBreadcrumb/docs-demo/DsfrBreadcrumbDemo.vue
Labels: documentation

#701 fix: :bug: ajoute condition pour affichage div.fr-footer__bottom-copy
  src/components/DsfrFooter/DsfrFooter.spec.ts
  src/components/DsfrFooter/DsfrFooter.vue
Labels: bug
