Repository dnum-mi/vue-dsfr, pull requests merged in 2024-09, with the labels that each got.

#913 feat(DsfrCard): ✨ permet d’ajouter des badges dans le header
  src/components/DsfrCard/DsfrCard.md
  src/components/DsfrCard/DsfrCard.spec.ts
  src/components/DsfrCard/DsfrCard.types.ts
  src/components/DsfrCard/DsfrCard.vue
  src/components/DsfrCard/docs-demo/DsfrCardDemo.vue
Labels: enhancement

#917 Develop
  src/components/DsfrCard/DsfrCard.md
  src/components/DsfrRadioButton/DsfrRadioButton.types.ts
  src/components/DsfrRadioButton/DsfrRadioButtonSet.md
  src/components/DsfrRadioButton/DsfrRadioButtonSet.vue
  src/components/DsfrRadioButton/docs-demo/DsfrRadioButtonSetDemo.vue
Labels: documentation, enhancement

#927 fix(DsfrNavigationMenuLink): 🐛 utilise onClick passé en prop
  demo-app/main.js
  demo-app/views/AppHome.vue
  src/components/DsfrAccordion/DsfrAccordionsGroup.vue
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrHeader/injection-key.ts
  src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
Labels: bug

#928 Develop
  ci/check-exports.mjs
  demo-app/main.js
  demo-app/views/AppHome.vue
  src/components/DsfrAccordion/DsfrAccordion.md
  src/components/DsfrAccordion/DsfrAccordion.vue
  src/components/DsfrAccordion/DsfrAccordionsGroup.vue
  src/components/DsfrAccordion/injection-key.ts
  src/components/DsfrHeader/DsfrHeader.md
  src/components/DsfrHeader/DsfrHeader.vue
  src/components/DsfrHeader/DsfrHeaderMenuLink.vue
  src/components/DsfrHeader/injection-key.ts
  src/components/DsfrNavigation/DsfrNavigationMenuLink.vue
  src/components/DsfrTabs/DsfrTabs.md
  src/components/index.ts
Labels: bug
